# Generated by Django 5.1.15 on 2026-09-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatedpayment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
