# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveragePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('plan_code', models.CharField(choices=[('THIRD_PARTY', 'Third-Party Liability Only'), ('COMPREHENSIVE', 'Comprehensive / Full Insurance'), ('ZERO_DEP_PREMIUM', 'Zero Depreciation Comprehensive')], default='COMPREHENSIVE', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('base_rate_percentage', models.DecimalField(decimal_places=3, help_text='Annual premium rate as percentage of vehicle IDV (e.g. 2.850%)', max_digits=5)),
                ('standard_deductible', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('includes_own_damage', models.BooleanField(default=True)),
                ('includes_third_party', models.BooleanField(default=True)),
                ('includes_roadside_assistance', models.BooleanField(default=False)),
                ('includes_engine_protection', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coverage Plan',
                'verbose_name_plural': 'Coverage Plans',
            },
        ),
        migrations.CreateModel(
            name='QuotationDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quotation_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('vehicle_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_years', models.PositiveIntegerField(choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years')], default=1)),
                ('calculated_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductible_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACCEPTED', 'Accepted by Customer'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to Policy')], db_index=True, default='DRAFT', max_length=20)),
                ('valid_until', models.DateTimeField()),
                ('coverage_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='quotations.coverageplan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='customers.customerprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Quotation Draft',
                'verbose_name_plural': 'Quotation Drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
