# Generated by Django 5.1.15 on 2026-09-14 04:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotationdraft_underwriter_coveragefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdraft',
            name='addon_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total premium for selected optional add-on riders in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationdraft',
            name='base_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base plan premium before optional riders in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationdraft',
            name='selected_features',
            field=models.ManyToManyField(blank=True, help_text='Itemized features and optional riders included in this quotation', related_name='quotations', to='quotations.coveragefeature'),
        ),
        migrations.AlterField(
            model_name='quotationdraft',
            name='calculated_premium',
            field=models.DecimalField(decimal_places=2, help_text='Total calculated premium in INR (Base + Add-ons)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationdraft',
            name='deductible_amount',
            field=models.DecimalField(decimal_places=2, help_text='Compulsory policy deductible in INR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationdraft',
            name='vehicle_value',
            field=models.DecimalField(decimal_places=2, help_text='Insured Declared Value (IDV) in INR', max_digits=12),
        ),
    ]
