# Generated by Django 5.1.15 on 2026-09-17 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotationdraft_addon_premium_and_more'),
        ('staff', '0003_branch_staffprofile_employee_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationdraft',
            name='underwriter',
        ),
        migrations.AddField(
            model_name='quotationdraft',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Staff member who prepared or reviewed this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='quotationdraft',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationdraft',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member or admin who reviewed this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
