# Generated by Django 5.1.15 on 2026-09-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequest_change_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('POLICY_RENEWAL', 'Policy Renewal Request'), ('ADDRESS_UPDATE', 'Address / Contact Update'), ('VEHICLE_UPDATE', 'Vehicle Information Update'), ('DOCUMENT_REQUEST', 'Policy Document / Certificate Request'), ('COVERAGE_CHANGE', 'Coverage / Endorsement Modification'), ('POLICY_SERVICE', 'Policy Service Query'), ('VEHICLE_SERVICE', 'Vehicle Service Query'), ('ENDORSEMENT', 'Endorsement / Modification'), ('OTHER', 'General Servicing Query')], db_index=True, default='POLICY_RENEWAL', max_length=30),
        ),
    ]
