# Generated by Django 5.1.15 on 2026-09-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='change_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Structured parameter changes for policy endorsement adjudication'),
        ),
    ]
