# Generated by Django 5.1.15 on 2026-09-17 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='driving_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer Not To Say')], max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nps_score', models.PositiveSmallIntegerField(help_text='NPS Score 0-10')),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('verification_type', models.CharField(choices=[('PAN', 'Permanent Account Number (PAN)')], default='PAN', max_length=30)),
                ('document_number_masked', models.CharField(help_text='Masked document identifier e.g. ABCDE****F', max_length=30)),
                ('provider', models.CharField(default='RAPIDAPI', max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PHONE_OTP_REQUIRED', 'Phone OTP Required'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=30)),
                ('name_match', models.BooleanField(blank=True, null=True)),
                ('dob_match', models.BooleanField(blank=True, null=True)),
                ('phone_match', models.BooleanField(blank=True, null=True)),
                ('verified_phone_masked', models.CharField(blank=True, help_text='Masked mobile number e.g. ******1234', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
