# Generated by Django 5.1.15 on 2026-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotptoken',
            name='purpose',
            field=models.CharField(default='LOGIN', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Customer'), ('STAFF', 'Staff'), ('ADMIN', 'Administrator')], db_index=True, default='USER', max_length=30),
        ),
    ]
