# Generated by Django 5.1.15 on 2026-09-14 04:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['staff_code'], 'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='designation',
            field=models.CharField(default='Operational Specialist', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(default='Operations', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_code',
            field=models.CharField(db_index=True, help_text='Unique employee identifier e.g., UW-102 or CH-405', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='ClaimsHandlerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_claim_approval_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Maximum single-claim settlement amount this handler can approve', max_digits=12)),
                ('active_claim_capacity', models.PositiveIntegerField(default=25, help_text='Maximum concurrent active claims this handler can hold in review')),
                ('specialization_team', models.CharField(default='General Claims', help_text='Specialized unit (e.g. Rapid Settlement, Total Loss, Bodily Injury)', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('staff_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claims_handler_profile', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Claims Handler Profile',
                'verbose_name_plural': 'Claims Handler Profiles',
            },
        ),
        migrations.CreateModel(
            name='UnderwriterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('underwriting_limit', models.DecimalField(decimal_places=2, default=Decimal('2500000.00'), help_text='Maximum vehicle IDV / policy coverage this underwriter can approve without escalation', max_digits=12)),
                ('license_number', models.CharField(blank=True, help_text='State or statutory insurance underwriting license code', max_length=50)),
                ('specialization', models.CharField(default='General Motor', help_text='Underwriting specialization (e.g. Commercial Fleets, Private Passenger, EV)', max_length=100)),
                ('portfolio_name', models.CharField(default='Standard Personal Lines', help_text='Assigned risk portfolio book of business', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('staff_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='underwriter_profile', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Underwriter Profile',
                'verbose_name_plural': 'Underwriter Profiles',
            },
        ),
    ]
