# Generated by Django 5.1.15 on 2026-09-17 16:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerprofile_options_and_more'),
        ('staff', '0002_alter_staffprofile_options_staffprofile_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('branch_opening_date', models.DateField(blank=True, null=True)),
                ('office_rent_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['state', 'city'],
            },
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employee_level',
            field=models.CharField(default='L1', max_length=30),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='performance_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='underwriterprofile',
            name='approval_authority_level',
            field=models.CharField(default='STANDARD', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('UNDERWRITING', 'Underwriting'), ('CLAIMS', 'Claims')], db_index=True, default='UNDERWRITING', max_length=30),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.branch'),
        ),
        migrations.CreateModel(
            name='StaffCustomerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred')], db_index=True, default='ACTIVE', max_length=20)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Administrator who executed the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Assigned customer profile', on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='customers.customerprofile')),
                ('staff', models.ForeignKey(help_text='Staff member assigned to this customer', on_delete=django.db.models.deletion.CASCADE, related_name='staff_customer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff-Customer Assignment',
                'verbose_name_plural': 'Staff-Customer Assignments',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('customer',), name='unique_active_staff_customer_assignment')],
            },
        ),
    ]
