# Generated by Django 5.1.15 on 2026-09-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('customers', '0001_initial'),
        ('policies', '0001_initial'),
        ('staff', '0002_alter_staffprofile_options_staffprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PENDING'), ('handler__isnull', False), _negated=True), name='chk_pending_claim_handler_null'),
        ),
    ]
