# Generated by Django 5.1.15 on 2026-09-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_chk_pending_claim_handler_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Assignment'), ('IN_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='claimevent',
            name='event_type',
            field=models.CharField(choices=[('CLAIM_CREATED', 'Claim Created'), ('CLAIM_ASSIGNED', 'Claim Assigned / Picked Up'), ('CLAIM_IN_REVIEW', 'Moved to Review'), ('CLAIM_REVIEW_STARTED', 'Claim Review Started'), ('DOCUMENT_ADDED', 'Document Uploaded'), ('CLAIM_APPROVED', 'Claim Approved by Handler'), ('CLAIM_REJECTED', 'Claim Rejected by Handler'), ('CLAIM_SETTLED', 'Claim Settled (Simulated Payout)'), ('CLAIM_NOTE_ADDED', 'Claim Note Added')], max_length=30),
        ),
    ]
