# Generated by Django 5.1.15 on 2026-09-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_status_alter_claimevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when claim simulated settlement was finalized', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='settlement_reference',
            field=models.CharField(blank=True, help_text='Simulated payment reference for settled claims', max_length=64),
        ),
    ]
