# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(default='Vehicle Insurance Assistance', max_length=150)),
                ('pending_transaction', models.JSONField(blank=True, help_text='Payload awaiting explicit customer confirmation before tool invocation', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'AI Assistant'), ('SYSTEM', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(default=list, help_text='Retrieved RAG knowledge chunks and policy references')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tool_name', models.CharField(db_index=True, max_length=60)),
                ('parameters', models.JSONField(default=dict)),
                ('execution_status', models.CharField(choices=[('PROPOSED', 'Proposed / Pending Confirmation'), ('CONFIRMED', 'Confirmed by Customer'), ('EXECUTED', 'Executed Successfully'), ('BLOCKED', 'Blocked by Guardrail'), ('FAILED', 'Failed')], default='PROPOSED', max_length=30)),
                ('result_payload', models.JSONField(default=dict)),
                ('guardrail_notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chatbot Tool Call',
                'verbose_name_plural': 'Chatbot Tool Calls',
                'ordering': ['-created_at'],
            },
        ),
    ]
