# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('POLICY_WORDING', 'Policy Wording & Definitions'), ('COVERAGE_DETAILS', 'Coverage Details & Exclusions'), ('CLAIM_PROCEDURE', 'Approved Claims Procedures'), ('CLAIM_DOCUMENT_REQ', 'Claim Document Requirements'), ('CLAIM_FAQ', 'Claim FAQs'), ('SERVICING_GUIDE', 'Policy Servicing Procedures'), ('RENEWAL_INFO', 'Renewal Rules & Procedures')], db_index=True, max_length=40)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('source_reference', models.CharField(max_length=255)),
                ('is_approved_for_rag', models.BooleanField(db_index=True, default=True)),
                ('content_raw', models.TextField(help_text='Full extracted text')),
            ],
            options={
                'verbose_name': 'Knowledge Document',
                'verbose_name_plural': 'Knowledge Documents',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('supabase_embedding_id', models.CharField(blank=True, help_text='Identifier in Supabase pgvector table', max_length=64, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Knowledge Chunk',
                'verbose_name_plural': 'Knowledge Chunks',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
