# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('quotations', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Suitability score (0.00 to 100.00)', max_digits=5)),
                ('rationale', models.TextField(help_text='Why this coverage is suited to the vehicle age, valuation, and usage')),
                ('assumptions', models.TextField(help_text='Key assumptions used to produce this recommendation')),
                ('disclaimer', models.TextField(default='Educational decision support only. Not guaranteed financial or statutory insurance advice.')),
                ('alternative_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_recommendations', to='quotations.coverageplan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='customers.customerprofile')),
                ('recommended_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_recommendations', to='quotations.coverageplan')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Coverage Recommendation',
                'verbose_name_plural': 'Coverage Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
