# Generated by Django 5.1.15 on 2026-09-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictions', '0003_predictionlog_requested_by'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragerecommendation',
            name='generated_by_model',
            field=models.CharField(blank=True, default='Nexisure-Coverage-v1', max_length=100),
        ),
        migrations.AddField(
            model_name='coveragerecommendation',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='predictions.modelversion'),
        ),
    ]
