# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('card_network', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover'), ('OTHER', 'Other / Unknown Network')], default='VISA', max_length=20)),
                ('masked_card_number', models.CharField(help_text='Masked card representation e.g., **** **** **** 4242', max_length=25)),
                ('simulated_transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('simulated_gateway_response', models.JSONField(default=dict)),
                ('disclaimer', models.TextField(default='Simulated educational payment demonstration. No real funds or sensitive card data are processed.')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='policies.policy')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='quotations.quotationdraft')),
            ],
            options={
                'verbose_name': 'Simulated Payment',
                'verbose_name_plural': 'Simulated Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
