# Generated by Django 5.1.15 on 2026-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_simulatedpayment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedpayment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking (Simulated)'), ('UPI', 'UPI (Simulated)')], default='CREDIT_CARD', max_length=30),
        ),
    ]
