# Generated by Django 5.1.15 on 2026-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_DELETED', 'Staff Deleted'), ('STAFF_REASSIGNED', 'Staff Workload Reassigned'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('USER_LOGIN', 'User Logged In'), ('USER_LOGOUT', 'User Logged Out'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('VEHICLE_CREATED', 'Vehicle Created'), ('VEHICLE_UPDATED', 'Vehicle Updated'), ('VEHICLE_DEACTIVATED', 'Vehicle Deactivated'), ('QUOTATION_CREATED', 'Quotation Created'), ('QUOTATION_ACCEPTED', 'Quotation Accepted'), ('POLICY_CREATED', 'Policy Created'), ('POLICY_UPDATED', 'Policy Updated'), ('POLICY_RENEWED', 'Policy Renewed'), ('POLICY_TYPE_CONVERTED', 'Policy Coverage Converted'), ('POLICY_REASSIGNED', 'Policy Underwriter Reassigned'), ('POLICY_CERTIFICATE_GENERATED', 'Policy Certificate Generated'), ('POLICY_ENDORSEMENT_REQUESTED', 'Policy Endorsement Requested'), ('POLICY_ENDORSEMENT_APPROVED', 'Policy Endorsement Approved'), ('POLICY_ENDORSEMENT_REJECTED', 'Policy Endorsement Rejected'), ('POLICY_CANCELLED', 'Policy Cancelled'), ('CLAIM_CREATED', 'Claim Created'), ('CLAIM_ASSIGNED', 'Claim Assigned / Picked Up'), ('CLAIM_REVIEW_STARTED', 'Claim Review Started'), ('CLAIM_APPROVED', 'Claim Approved'), ('CLAIM_REJECTED', 'Claim Rejected'), ('CLAIM_DOCUMENT_ADDED', 'Claim Document Added'), ('CLAIM_NOTE_ADDED', 'Claim Note Added'), ('CLAIM_SETTLED', 'Claim Settled'), ('SERVICE_REQUEST_CREATED', 'Service Request Created'), ('SERVICE_REQUEST_UPDATED', 'Service Request Updated'), ('SERVICE_REQUEST_RESOLVED', 'Service Request Resolved'), ('SERVICE_REQUEST_REJECTED', 'Service Request Rejected'), ('KYC_VERIFICATION_STARTED', 'KYC Verification Started'), ('KYC_VERIFIED', 'KYC Verified'), ('KYC_FAILED', 'KYC Verification Failed'), ('USER_REGISTERED', 'User Registered'), ('CUSTOMER_ASSIGNED', 'Customer Assigned to Staff'), ('CUSTOMER_TRANSFERRED', 'Customer Transferred to Staff'), ('CUSTOMER_UNASSIGNED', 'Customer Unassigned from Staff'), ('STAFF_SUSPENDED', 'Staff Suspended'), ('CHATBOT_TOOL_EXECUTED', 'Chatbot Tool Executed'), ('PREDICTION_CREATED', 'ML Prediction Created'), ('MODEL_VERSION_PROMOTED', 'Model Version Promoted'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('VEHICLE_LOOKUP', 'Vehicle Registry Lookup')], db_index=True, max_length=60),
        ),
    ]
