# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('policies', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('claim_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('incident_date', models.DateTimeField(db_index=True)),
                ('incident_location', models.CharField(max_length=255)),
                ('incident_description', models.TextField()),
                ('estimated_loss_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Authorized payout finalized by human claims handler', max_digits=12, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('IN_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='customers.customerprofile')),
                ('handler', models.ForeignKey(blank=True, help_text='Claims handler assigned to this claim; null while in pending queue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_claims', to='staff.staffprofile')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('document_type', models.CharField(choices=[('POLICE_REPORT', 'Police First Information Report'), ('DAMAGE_PHOTO', 'Vehicle Damage Photo'), ('REPAIR_ESTIMATE', 'Repair Garage Estimate'), ('DRIVING_LICENSE', 'Driver License Copy'), ('OTHER', 'Other Supporting Document')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='claims/documents/%Y/%m/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Claim Document',
                'verbose_name_plural': 'Claim Documents',
            },
        ),
        migrations.CreateModel(
            name='ClaimEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event_type', models.CharField(choices=[('CLAIM_CREATED', 'Claim Created'), ('CLAIM_ASSIGNED', 'Claim Assigned / Picked Up'), ('CLAIM_IN_REVIEW', 'Moved to Review'), ('DOCUMENT_ADDED', 'Document Uploaded'), ('CLAIM_APPROVED', 'Claim Approved by Handler'), ('CLAIM_REJECTED', 'Claim Rejected by Handler')], max_length=30)),
                ('actor_role', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Claim Event',
                'verbose_name_plural': 'Claim Events',
                'ordering': ['created_at'],
            },
        ),
    ]
