# Generated by Django 5.1.15 on 2026-09-17 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_settled_at_claim_settlement_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_severity',
            field=models.CharField(default='MODERATE', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('ACCIDENT', 'Accident / Collision'), ('THEFT', 'Vehicle Theft'), ('FIRE', 'Fire Damage'), ('NATURAL_DISASTER', 'Natural Disaster / Flood')], db_index=True, default='ACCIDENT', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_claim_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_claim_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
