# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('registration_number', models.CharField(db_index=True, help_text='Normalized uppercase license plate (e.g. DL01AB1234)', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('COMMERCIAL_VAN', 'Commercial Van')], default='SEDAN', max_length=30)),
                ('make', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('manufacture_year', models.PositiveIntegerField(db_index=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric (EV)'), ('HYBRID', 'Hybrid'), ('CNG', 'CNG')], default='PETROL', max_length=20)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('chassis_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_value', models.DecimalField(decimal_places=2, help_text='Insured Declared Value (IDV)', max_digits=12)),
                ('usage_type', models.CharField(choices=[('PERSONAL', 'Personal Commute'), ('COMMERCIAL', 'Commercial Business'), ('RIDESHARE', 'Rideshare / Taxi')], default='PERSONAL', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customerprofile')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
