# Generated by Django 5.1.15 on 2026-09-17 16:11

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('vehicle_theft_rate_area', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('accident_hotspot_flag', models.BooleanField(default=False)),
                ('avg_repair_cost_area', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Area Risk',
                'verbose_name_plural': 'Area Risks',
                'ordering': ['state', 'city'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModelSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('make', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(db_index=True, max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('segment', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('engine_type', models.CharField(blank=True, max_length=50)),
                ('displacement', models.PositiveIntegerField(blank=True, null=True)),
                ('cylinder', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transmission_type', models.CharField(blank=True, max_length=30)),
                ('gear_box', models.CharField(blank=True, max_length=30)),
                ('max_power', models.CharField(blank=True, max_length=50)),
                ('max_torque', models.CharField(blank=True, max_length=50)),
                ('gross_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('airbags', models.PositiveSmallIntegerField(default=2)),
                ('is_esc', models.BooleanField(default=False)),
                ('is_tpms', models.BooleanField(default=False)),
                ('is_parking_sensors', models.BooleanField(default=False)),
                ('is_parking_camera', models.BooleanField(default=False)),
                ('ncap_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Vehicle Model Specification',
                'verbose_name_plural': 'Vehicle Model Specifications',
                'ordering': ['make', 'model', 'variant'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='variant',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
