# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('quotations', '0001_initial'),
        ('staff', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('policy_number', models.CharField(db_index=True, help_text='Unique policy identifier (e.g. POL-2026-100234)', max_length=40, unique=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, help_text='Locked premium amount for this policy term', max_digits=10)),
                ('deductible_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_years', models.PositiveIntegerField(choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years')], default=1)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('RENEWED', 'Renewed')], db_index=True, default='ACTIVE', max_length=20)),
                ('coverage_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='quotations.coverageplan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='customers.customerprofile')),
                ('previous_policy', models.ForeignKey(blank=True, help_text='Lineage tracking for renewal history without mutating past records', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_history', to='policies.policy')),
                ('underwriter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underwritten_policies', to='staff.staffprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
