# Generated by Django 5.1.15 on 2026-09-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('policies', '0001_initial'),
        ('quotations', '0001_initial'),
        ('staff', '0002_alter_staffprofile_options_staffprofile_designation_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='chk_policy_dates'),
        ),
    ]
