# Generated by Django 5.1.15 on 2026-09-17 16:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_chk_policy_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('addon_name', models.CharField(max_length=100)),
                ('addon_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('addon_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Addon',
                'verbose_name_plural': 'Addons',
                'ordering': ['addon_name'],
            },
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='underwriter',
            new_name='assigned_staff',
        ),
        migrations.AddField(
            model_name='policy',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LAPSED', 'Lapsed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='PolicyAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_instances', to='policies.addon')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_addons', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Policy Addon',
                'verbose_name_plural': 'Policy Addons',
                'constraints': [models.UniqueConstraint(fields=('policy', 'addon'), name='unique_policy_addon')],
            },
        ),
    ]
