# Generated by Django 5.1.15 on 2026-09-13 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(choices=[('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_DELETED', 'Staff Deleted'), ('STAFF_REASSIGNED', 'Staff Workload Reassigned'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('POLICY_CREATED', 'Policy Created'), ('POLICY_UPDATED', 'Policy Updated'), ('POLICY_RENEWED', 'Policy Renewed'), ('POLICY_TYPE_CONVERTED', 'Policy Coverage Converted'), ('POLICY_REASSIGNED', 'Policy Underwriter Reassigned'), ('CLAIM_CREATED', 'Claim Created'), ('CLAIM_ASSIGNED', 'Claim Assigned / Picked Up'), ('CLAIM_APPROVED', 'Claim Approved'), ('CLAIM_REJECTED', 'Claim Rejected'), ('SERVICE_REQUEST_CREATED', 'Service Request Created'), ('SERVICE_REQUEST_UPDATED', 'Service Request Updated'), ('CHATBOT_TOOL_EXECUTED', 'Chatbot Tool Executed'), ('PREDICTION_CREATED', 'ML Prediction Created')], db_index=True, max_length=60)),
                ('target_entity', models.CharField(db_index=True, max_length=60)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
