# Generated by Django 5.1.15 on 2026-09-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_DELETED', 'Staff Deleted'), ('STAFF_REASSIGNED', 'Staff Workload Reassigned'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('VEHICLE_CREATED', 'Vehicle Created'), ('VEHICLE_UPDATED', 'Vehicle Updated'), ('VEHICLE_DEACTIVATED', 'Vehicle Deactivated'), ('QUOTATION_CREATED', 'Quotation Created'), ('QUOTATION_ACCEPTED', 'Quotation Accepted'), ('POLICY_CREATED', 'Policy Created'), ('POLICY_UPDATED', 'Policy Updated'), ('POLICY_RENEWED', 'Policy Renewed'), ('POLICY_TYPE_CONVERTED', 'Policy Coverage Converted'), ('POLICY_REASSIGNED', 'Policy Underwriter Reassigned'), ('CLAIM_CREATED', 'Claim Created'), ('CLAIM_ASSIGNED', 'Claim Assigned / Picked Up'), ('CLAIM_APPROVED', 'Claim Approved'), ('CLAIM_REJECTED', 'Claim Rejected'), ('SERVICE_REQUEST_CREATED', 'Service Request Created'), ('SERVICE_REQUEST_UPDATED', 'Service Request Updated'), ('CHATBOT_TOOL_EXECUTED', 'Chatbot Tool Executed'), ('PREDICTION_CREATED', 'ML Prediction Created'), ('MODEL_VERSION_PROMOTED', 'Model Version Promoted'), ('PAYMENT_PROCESSED', 'Payment Processed')], db_index=True, max_length=60),
        ),
    ]
