# Generated by Django 5.1.15 on 2026-09-14 04:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
        ('staff', '0002_alter_staffprofile_options_staffprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdraft',
            name='underwriter',
            field=models.ForeignKey(blank=True, help_text='Underwriter who prepared or reviewed this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='staff.staffprofile'),
        ),
        migrations.CreateModel(
            name='CoverageFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('feature_code', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_standard', models.BooleanField(default=True, help_text='True if included as standard; False if optional add-on rider')),
                ('add_on_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional premium if optional rider', max_digits=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='quotations.coverageplan')),
            ],
            options={
                'verbose_name': 'Coverage Feature',
                'verbose_name_plural': 'Coverage Features',
                'ordering': ['plan', 'title'],
                'unique_together': {('plan', 'feature_code')},
            },
        ),
    ]
